parameters:
#    jacms_page.example.class: Jacms\PageBundle\Example

services:
#    jacms_page.example:
#        class: %jacms_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
